"use client";
import dynamic from "next/dynamic";
import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import { Inter } from "next/font/google";
import {
  DynamicContextProvider,
  EthereumWalletConnectors,
  DynamicWagmiConnector,
} from "../lib/dynamic.js";
import { LoginModal } from "../components/modal/LoginModal";
import { AudioControlBar } from "../components/AudioControlBar";
import GetPageProvider from "../contexts/PageContext";
import GetUserDataProvider from "../contexts/UserDataContext";
import { SideBarSkeleton } from "../components/Sidebar/skeleton";
import { Providers } from "./providers";
import "react-multi-carousel/lib/styles.css";
import "react-loading-skeleton/dist/skeleton.css";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PXLTUNZ",
  description: "Generated by PXLTUNZ Team",
};

const Sidebar = dynamic(() => import("../components/Sidebar"), {
  ssr: false,
  loading: () => <SideBarSkeleton />,
});

const Header = dynamic(() => import("../components/Header"), {
  ssr: false,
  loading: () => <></>,
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + ` flex w-full relative`}>
        <DynamicContextProvider
          settings={{
            environmentId: process.env.NEXT_PUBLIC_DYNAMIC_ENVIROMENT_ID!,
            walletConnectors: [EthereumWalletConnectors],
          }}
        >
          <Providers>
            <DynamicWagmiConnector>
              <GetPageProvider>
                <GetUserDataProvider>
                  <ToastContainer />
                  <Sidebar />
                  <Header />
                  {children}
                  <AudioControlBar />
                  <LoginModal />
                </GetUserDataProvider>
              </GetPageProvider>
            </DynamicWagmiConnector>
          </Providers>
        </DynamicContextProvider>
      </body>
    </html>
  );
}
